### ISSUE TITLE
Invalid Secp256k1 pubkey length (compressed): 0

### ISSUE THREAD

**Issue by kristovatlas** [cosmos/cosmos-multisig-ui#211]
When trying to create a multisig address using https://multisig.confio.run/saga/create :

I get this error message:
`Invalid Secp256k1 pubkey length (compressed): 0`

Additional browser console output:
```
Access to fetch at 'https://rpc-saga.keplr.app/' from origin 'https://multisig.confio.run' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
rpc-saga.keplr.app/:1 
        
        
       Failed to load resource: net::ERR_FAILED
create:1 Access to fetch at 'https://saga-mainnet-rpc.autostake.com/' from origin 'https://multisig.confio.run' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
saga-mainnet-rpc.autostake.com/:1 
        
        
       Failed to load resource: net::ERR_FAILED
create-e00a699a23c81075.js:1 Object
create-e00a699a23c81075.js:1 Object
create-e00a699a23c81075.js:1 Object
create-e00a699a23c81075.js:1 Object
create-e00a699a23c81075.js:1 Object
create-e00a699a23c81075.js:1 Object
create-e00a699a23c81075.js:1 Object
create-e00a699a23c81075.js:1 Object
create-e00a699a23c81075.js:1 Object
create-e00a699a23c81075.js:1 Object
create-e00a699a23c81075.js:1 Object
create-e00a699a23c81075.js:1 Failed to create multisig: Error: Invalid Secp256k1 pubkey length (compressed): 0
    at ep (_app-fab72fd75982dedc.js:1:57844)
    at ey (_app-fab72fd75982dedc.js:1:58045)
    at _app-fab72fd75982dedc.js:1:67945
    at Array.sort (<anonymous>)
    at ef (_app-fab72fd75982dedc.js:1:67898)
    at s (28-bed7607b75d4c8fc.js:1:11032)
    at P (create-e00a699a23c81075.js:1:6523)
    at Object.eU (framework-5866cead997b9ace.js:9:14910)
    at eH (framework-5866cead997b9ace.js:9:15064)
    at framework-5866cead997b9ace.js:9:33370
P @ create-e00a699a23c81075.js:1
create-e00a699a23c81075.js:1 Object
```

Both addresses I'm adding to the 2-of-2 multisig were generated using Keplr wallet. Browser is Brave (Chromium-based) for MacOS.

**Comment by webmaster128** [comment]
Thank you for the report. The issue is most likely caused by the pubkey not being on the chain (and the error handling failing). Could you try using the May Account  page (top right) to see the public keys and construct the multisig with pubkeys instead of addresses?

**Comment by abefernan** [comment]
Improved the multisig creation in #213 and the multisig error handling in #214
